### ISSUE TITLE
Include language codes in Textpacks repo

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpacks#108]
Currently, RPC Textpacks include localised translations for each language name (e.g., `el-gr => Ελληνικά` for Greek). The repo copy does not include this info - should it?

**Comment by Bloke** [comment]
I believe they should as they're used to localise the language list in the Languages panel, and probably during setup too.

But I think (I may be wrong) that they've been yanked out of the individual repo files and put in a separate location because they're all the same, for every language. My guess is that a script combines them prior to upload to RPC. Phil can confirm if that's the case.

**Comment by philwareham** [comment]
Yes , confirming what Stef said. The language names are not required in this repo.

Please ignore the RPC branch, it's for my own personal work in fixing up the RPC database.

**Comment by petecooper** [comment]
Thanks, @philwareham.
