### ISSUE TITLE
Missing strings 4.6

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpacks#113]
Need to add these strings:

    skin_base_path (prefs - also needs pophelp doc)
    default_publish_status (prefs - also needs pophelp doc)
    tab_skins (skin/theme - also needs pophelp doc)
    create_skin (skin/theme)
    edit_skin (skin/theme)
    skin_name (skin/theme)
    skin_title (skin/theme)
    skin_version (skin/theme)
    skin_author (skin/theme)
    skin_website (skin/theme)

More may be added as I spot them.

_Edit_: above strings added in https://github.com/textpattern/textpacks/commit/b2edd1ba735dfe6e1bad28c2c289264d1617af55 --@petecooper

**Comment by Bloke** [comment]
Do we need to translate things like `upload_tmp_dir` and `open_basedir`? They refer to specific folders in the Txp installation or specific features of PHP, so any translation will just be the same. The only possible advantage would be for RTL languages I suppose, because currently the colon is hard-coded after the string. But if there was a better way (e.g. getting rid of the colons) it would save having to add new strings for which translations would be identical.

**Comment by philwareham** [comment]
I don't think we do, I will remove `upload_tmp_dir` from the list. It makes no difference to RTL languages since the diagnostics panel is always LTR no matter what language it is in.

**Comment by petecooper** [comment]
@philwareham I've added these strings to `en-gb`:

```
skin_base_path
default_publish_status
tab_skins
create_skin
edit_skin
skin_name
skin_title
skin_version
skin_author
skin_website
```

Note: no translations at this stage. If you're happy with the placement within the `en-gb` Textpack, let me know and I'll add them to the other Textpacks in the same manner.

**Comment by philwareham** [comment]
Cheers Pete, I also need to find and list the strings needed for the admin layout update branch.

**Comment by Bloke** [comment]
Just a note: anything with 'skin' in it relates to public Themes which aren't due just yet. So these can stay on the back burner.

**Comment by philwareham** [comment]
True, there may be a case to leave them on a branch right now and not in 4.6 Textpacks.

**Comment by petecooper** [comment]
Let's leave them in. Much of the work has been done for skins and it's trivial to tweak once they're in. Folks know skins are in the pipeline and it won't hurt to get a head start. L

**Comment by Bloke** [comment]
That's absolutely fine by me. Just didn't want it to potentially impact your stat targets for the 4.6.0 drop date, especially since the Themes code isn't finalised yet.

**Comment by petecooper** [comment]
It's all good, @Bloke.

**Comment by philwareham** [comment]
More strings needed:

    all_preferences
    create_article
    search_articles
    search_images
    search_files
    search_links
    search_comments
    search_sections
    search_users
    search_logs

**Comment by petecooper** [comment]
@philwareham If you can indicate where each of the outstanding strings in https://github.com/textpattern/textpacks/issues/113#issuecomment-147658959 live in the Textpack section-wise, I'll crack on with that.

For clarification, have `all_preferences` and `create_article` been removed or merged, because I can't see either in `en-gb`.

**Comment by philwareham** [comment]
Hi Pete, sorry I've not added any of those strings into Textpacks yet.

**Comment by petecooper** [comment]
That's cool, I'm just checking to see if `all_preferences` and `create_article` were intended to go in and were removed form code, or something else - they're strikethrough'd.

I'll get the other strings in and if they need to relocate into a different section then that's straightforward enough to do. If you can let me know the situation with `all_preferences` and `create_article` (add, don't add, whatever) then I'll deal with them, too.

**Comment by philwareham** [comment]
all_preferences definitely needs adding. create_article is already in (I might have lab led it slightly differently in the end but it's there).

**Comment by petecooper** [comment]
Got it.

**Comment by petecooper** [comment]
@philwareham Regarding strings in https://github.com/textpattern/textpacks/issues/113#issuecomment-147658959, each is referenced in admin-side area with the exception of `publish_date` and `publish_time` which appears in article and file (currently, at least).

I will take the task of merging new strings, but it'd be useful to know where they should be section-wise. When time allows, could you tack on the section to the list, like you did in the OP, and I will deal. If you want to do it yourself, that's totally fine - just let me know. Thanks.

**Comment by philwareham** [comment]
Hi Pete, `publish_date` and `publish_time` should go in the `common` section.

**Comment by petecooper** [comment]
I was thinking broadly the same thing on `search_*`, so thanks for clarification.

**Comment by Bloke** [comment]
Couple more: see [Issue 553](https://github.com/textpattern/textpattern/issues/553) and its [corresponding commit](https://github.com/textpattern/textpattern/commit/59997ccd3b8bfeb74ede4ba3ac653b644c640b7e) for details.

**Comment by petecooper** [comment]
Question, please. What's preferable for you two (@Bloke and @philwareham) for adding these new strings:

* one issue to rule them all (this one)
* one issue per string, or small chunk of strings

I'm tending toward the latter for an audit trail and granularity, but I don't want to slow momentum. There are double-figures of new strings added already and this number will likely grow before 4.6 is ready to go.

I know there numerous short-lived issues where something is identified and almost instantly fixed with a PR or commit, and @rwetzlmayr immediately springs to mind when I think of these instances, and this route would save combing through catch-all issues.

Your input, gentlemen, is appreciated. Thanks.

**Comment by petecooper** [comment]
@Bloke -- re: https://github.com/textpattern/textpacks/issues/113#issuecomment-155583707 -- strings already present, unless I'm missing something (line 696 onwards, at present):

```
permalink_title_format => Permalink title-like-this (instead of TitleLikeThis)?
permlink_format => Permalink title URL pattern
permlink_hyphenated => Hyphenated (title-like-this)
permlink_intercapped => Intercapped (TitleLikeThis)
```

**Comment by Bloke** [comment]
Apologies, Sir. They weren't in the list in this issue so I didn't look in the actual files. Schoolboy error on my part.

**Comment by philwareham** [comment]
This issue is becoming confusingly long for all concerned. Will split the missing strings into more manageable issues. Closing.
