### ISSUE TITLE
Language codes too opinionated

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpacks#162]
At Textpattern v4.7 we have the opportunity to correct the language codes, due to severing the link to RPC server reliance.

At the moment languages are referenced with country codes - this assumes that the language is tied to a specific country even when it isn't desirable.

For example, English is currently labelled as either:

* en-GB
* en-US

This gives no allowance for countries where English is natively spoken (e.g. Australia, Canada) , or for multilingual sites where English is a country's second language (e.g. India, Nigeria).

The correct route would be to have the following:

* en
* en-GB
* en-US

This could be extended with (if contributed):

* en-AU
* en-CA
* en-NZ
* en-ZA

Although I do not foresee major differences with the above - there are potentially differences. This also corrects the hard-coded `lang` code in themes - which for example currently would give false `en-GB` if British English was selected but the site was actually supposed to be targeting an Australian audience.

Other languages that currently have this problem at least include...

* fr-FR
* de-DE
* ar-DZ

...although you could argue that all of the current Textpacks that are not tied to a specific dialect should have their country code removed.

**Comment by rwetzlmayr** [comment]
The `textpack` script currently uses en-gb.textpack as a [master template](https://github.com/textpattern/textpacks/blob/0f1120964ebdfd8a631476c656fd2fb5506ef9d2/textpack#L6). What would be the template file under these new file naming rules?

**Comment by philwareham** [comment]
The `en.textpack` would be the default template file going forward.

**Comment by Bloke** [comment]
This is going to cause hassle. Anybody who has already installed an opinionated language is going to get confusing information.

Example: I have `he-il` installed in 4.6.2, for testing RTL. I upgrade to 4.7.0, open the Languages panel and it shows "Installed: he-il" then underneath in the remainder of the grid it offers me the option to install `he`. Same language, different name.

What do we do?

* Somehow figure out (or have a map) that `he-il` is the same as `he`, and rename all strings in the db to remove the `-il` bit during upgrade.
* Assume that if the user has installed an opinionated language and we don't have such an equivalently named file, that ones with the same prefix are equivalent. This is tricky, since when we iterate over the list of files, we don't know what's coming next. E.g user has `en-gb` installed. We iterate over files in the `lang` directory and find `en`. Aha, it matches. Let's assume it's equivalent, overwrite the metadata. Next is `en-au`. No match. Next is `en-gb`. No match (because metadata has been overwritten by `en`). Oops.
* Force the user to uninstall old languages first before installing the 'correct' code. But that'll remove plugin strings too.
* Something else...?

Not sure how to approach this.

**Comment by philwareham** [comment]
Option 1 would get my vote. It's a shame the languages stuff was set up so badly in the first place that we have to jump through hoops to fix it (there are also 4.6 Textpacks that use country/language codes that don't even exist in ISO standards).
