### ISSUE TITLE
New tag trace strings

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpacks#205]
The tag trace seems to have introduced some new strings that need to be added to Textpacks:

    ambiguous_tag
    lonely_closing_tag
    tag_mismatch
    unclosed_tag
    unregistered_tag

@vanmelick @Bloke @bloatware can hopefully provide some text for the above, as I'm unsure as to their context.

**Comment by bloatware** [comment]
I can only describe the context:

* `ambiguous_tag`: is a tag like `</txp:tag />` closing or self-closed?
* `lonely_closing_tag`: a closing `</txp:tag>` without corresponding opening `<txp:tag>`
* `tag_mismatch`: an opening `<txp:tag1>` tag closed by `</txp:tag2>`
* `unclosed_tag`: an opening `<txp:tag>` without corresponding closing `</txp:tag>`
* `unregistered_tag`: a tag not declared as such by plugin.

**Comment by bloatware** [comment]
These are currently used only in Trace log, since the corresponding errors are recovered by the parser anyway. Should we output or merely dump them? I'm getting a little anxious about increasing verbosity/performance ratio.

**Comment by philwareham** [comment]
Sure, I feel we can dump them to cut overhead.

Either hardcode them in English or leave the `gTxt()` strings empty - which way do you want to handle it?

Probably similar behaviour for some of the diagnostics strings too - I'm sure a few of those could be pruned.

**Comment by Bloke** [comment]
I say leave them hard-coded in English. It's diagnostics/debug info. Same with the `assert_` strings: they shouldn't go through `gTxt()`, imo.

Yes, it's not particularly nice for people that don't speak the lingo to see English language error messages, but as Oleg says, how far do we go with translating system-level stuff?

**Comment by philwareham** [comment]
OK, I've removed the `assert_` strings. Let me know what else to remove once you've hardcoded them. Be ruthless! Debug info is fine in English IMO, as code tends to be English in nature (rightly or wrongly).

**Comment by bloatware** [comment]
I agree they should be in the same language that PHP warnings (always English?), but not hard-coded. Let's put them in some separate file/table that will be loaded only in non-live mode?

**Comment by philwareham** [comment]
OK, I bow to your greater understanding and ability here. If you create a file and format for it I'll populate the strings.

**Comment by bloatware** [comment]
JSON? It's easy to write/import, and can be modified (by someone more English-versed than me) without touching PHP code.

**Comment by philwareham** [comment]
OK sound fine to me. Although I'm conscious that we use a non-standard format for Textpacks, XML format for Pophelps, now JSON format possibly for this!!

**Comment by Bloke** [comment]
Okay, yeah, for clarity I meant 'hard-coded' in the sense that they're not translated but hard-coded in English, not hard-coded inside the code itself. Bad choice of words, sorry.

If you can find a logical place to store such English strings, and have it only loaded in testing/debugging mode, that's wonderful. I concur with Phil that'd be useful to have them in a consistent format with other "help" info, as we can use existing Txp functionality to parse them (though `json_decode()` is of course a PHP feature itself!)

**Comment by Bloke** [comment]
Not wishing to derail the conversation but it's an interesting point about the Textpack file format, btw. The other day I partly wished it could be an `.ini` file because then they can be read using `parse_ini_file()` and we can easily extract each section if necessary.

But `.ini` isn't necessarily that useful. Maybe one day we can work on migrating the lang files to a better format? Perhaps XML would be useful if we could compile them from Crowdin somehow? Splitting the file into `<group>`s and stuff would be helpful. It would also benefit us as we could put the metadata about each language in the first row or header block as attributes. That'd be more robust than currently relying on the first 3 or 4 lines - a fact that's hard-coded (in the true sense of the word) in the Textpack parser.

**Comment by bloatware** [comment]
Interesting. I've heard that JSON parsing is faster than XML (due to smaller size?). XML is certainly more flexible, but JSON seems to suffice for debug strings atm (no attributes, etc). Never parsed `.ini`, but this could be another option.

Atm I've found 44 strings used only in testing/debug mode.

**Comment by Bloke** [comment]
JSON is fine for debug strings... and wow, 44: that's a considerable saving for translators. Nice.

**Comment by bloatware** [comment]
I have finally moved them to new `config.ini` file: more human-readable/writable than JSON. Atm only `en.txt` has these ~40 strings removed (I have probably overlooked a few). If everything is fine, we can remove them from all languages. Then please add eventual new "debug" strings (in English) to `config.ini`.
