### ISSUE TITLE
Add or modify strings for Nginx support

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpacks#226]
Support for Nginx is coming in 4.7, and at the time of writing there are no Nginx-specific gTxt strings in Textpacks.

Considerations:
* it's possible to have Apache and Nginx running on the same server, so reporting diagnostics for both might create some challenges
* do we need a sensible way to ascertain which HTTP server Textpattern is using, and report appropriately?
* do we make some of the Apache references less specific to Apache (e.g. switch `Apache` out for `web server` or `http server` or similar)
* do we shoot for basic support in 4.7 and improve text strings for point releases thereafter?

As always, your advice and feedback is appreciated.

**Comment by philwareham** [comment]
@petecooper valid points all. I can run Apache and Nginx side-by-side in MAMP to test, although I have tended not to. I think of the above considerations, making the Apache references less specific to Apache is definitely a good starting point.

@makss did the Nginx initial support didn't he? Maybe he can give some further advice?

**Comment by Bloke** [comment]
Agree. If we can determine without a shadow of doubt which is in use for an instance of Textpattern, then maybe we can employ {replacement} syntax in any messages to indicate which one. Otherwise, unless the reference is specific to Apache, generalise it to 'web server' or some well-known phrase.

I'd like Diagnostics to be able to report appropriately but I don't know how reliable the apache/nginx-specific checks are in PHP. Presumably the actual functions are robust enough, but maybe some hosts turn various calls on or off dependent on their infrastructure? Haven't tested that. Maybe we use '@' in the code when using these functions, just in case... can't remember.

If the two web hosting technologies can run side-by-side, presumably any instance of Textpattern can only use one at once, right? So, in theory, it ought to be possible to ask "hey, server, which one ya usin' for me?"

**Comment by makss** [comment]
It's not entirely clear what the question is, we have diagnostics reporting which web server is used:

```
Server: Apache/2.2.15 (CentOS)
Apache version: Apache/2.2.15 (CentOS)
PHP server API: apache2handler
```

```
Server: nginx/1.8.1
PHP server API: fpm-fcgi
```

PHP Built-in web server: `php 0.0.0.0:80`
```
Server: PHP 5.5.38 Development Server
PHP server API: cli-server
```
I think that other web servers will work fine: lighttpd, hhvm, etc.

BTW, the message `cleanurl_only_apache` can be deleted.

**Comment by philwareham** [comment]
Is this issue completed now? Can't remember.

**Comment by petecooper** [comment]
Done, as far as I can tell.
