### ISSUE TITLE
Remove unused strings

### ISSUE THREAD

**Issue by bloatware** [textpattern/textpacks#238]
About 45 "debug" strings have moved from `en.txt` to `config.ini` in `textpattern/textpattern` repository. If everything is fine, other languages should be synced with `en.txt`.

I have also noticed that some strings (like `unknown_author`) don't seem to be used anymore. Audit, someone?

**Comment by philwareham** [comment]
I did an audit about a year or so ago. I guess a few strings have been obsoleted since then. I'll remove `unknown_author` but short of doing a full manual audit again (something I'm not keen on undertaking right now) is there an easy way of determining unused strings (i.e. via some PHP/Node.js/Perl)?

**Comment by makss** [comment]
> is there an easy way of determining unused strings (i.e. via some PHP/Node.js/Perl)?

I solve a similar problem, only I make a list of all the callbacks. I think that these two tasks can be combined.

**Comment by philwareham** [comment]
There is a tool already which achieves part of this - maybe it can be expanded in scope?...

https://github.com/textpattern/textpacks/tree/master/tools

**Comment by philwareham** [comment]
I've audited the common section now and removed any unused/legacy strings. Closing.
