### ISSUE TITLE
textpack_strings_installed in wrong group?

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpacks#265]
It seems the `textpack_strings_installed` key is in the `[prefs]` group when it should be in `[lang]`. It also requires a full stop.

**Comment by philwareham** [comment]
Fcuks sake. OK, I'll fix this - but can you let me know f there is any decision on the 'Override' theme panel string that was discussed in forum? If I have to reconfigure Crowdin anyway, I might as well do any change to that as well, otherwise I'll need to reconfigure again. Also, web hook URLs - if I need to do a new pref text for that (i.e. so user can set a secret key/API key) I'd like to do at same time.

**Comment by Bloke** [comment]
Sorry.

Nobody seems to have any opinion either way on the override thing. Must just be me that thinks it's off. I can live with it.

**Comment by Bloke** [comment]
P.S. @philwareham Did you get my email about the Textpack on the Plugins panel? Or did the Internet eat it because of the attached code?

**Comment by philwareham** [comment]
Hiya, yep I got it. Will read through tomorrow and see what I can do.

FWIW I'm not keen on the 'Override' term either. Took me a while to work out what it actually did. It should be 'Rebuild' I think.

**Comment by Bloke** [comment]
I'm fine with 'Rebuild' if we can fashion suitable message(s) that satisfy as much of [the theme/file workflow](https://forum.textpattern.io/viewtopic.php?pid=309992#p309992) as possible. Rebuild kinda doesn't work for the 'delete' case, but as Meatloaf says, two out of three ain't bad.

**Comment by philwareham** [comment]
Move "Resynchronise' then?

**Comment by Bloke** [comment]
Oooh, that has merit. Me likee.

**Comment by philwareham** [comment]
Done. Closing.
