### ISSUE TITLE
Unparsed string: `must_reassign_assets`

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpacks#272]
STR:

* delete an author, assign assets to nobody

SFW screencast attached.

[must_reassign_assets.mp4.zip](https://github.com/textpattern/textpacks/files/2073247/must_reassign_assets.mp4.zip)

**Comment by petecooper** [comment]
Actually this string is not missing - line 37 currently. It's in the `admin` block, so what gives?

**Comment by philwareham** [comment]
@bloke any ideas on this one?

**Comment by Bloke** [comment]
Bug. Thanks, Pete. Also affects deletion when trying to reassign an account to the same one as being deleted (`cannot_assign_assets_to_deletee`).

In txp_admin's multi-edit code, we assign the  gTxt string we need to a variable in the `switch()` statement but it's _only_ passed through `gTxt()` if the `$changed` variable is set. Otherwise it's passed verbatim back to the `author_list()` so it's being displayed as such.

We need to either:
1. Set `$changed` in these two cases and (possibly) alter the strings so they accept a `{name}` argument to show which assets were affected.
2. Just pass these two error strings through `gTxt()` when they're created.

Will fix.

**Comment by petecooper** [comment]
Nice one @Bloke - appreciated!

**Comment by petecooper** [comment]
>we should file a related bug in the main textpattern repo and reference this one, as it's not actually a Textpack bug as such, though it may impact it.

@Bloke - do you recall if the issue was opened in 
https://github.com/textpattern/textpattern ? If not, shall I take it?
