### ISSUE TITLE
Secondpass string needed?

### ISSUE THREAD

**Issue by bloatware** [textpattern/textpacks#296]
I have exposed a previously hidden advanced `secondpass` pref that translates as `Number of extra parser passes`. Not sure a string is needed for it, since the aim is to test and see whether we can get rid of extra passes (and then of this pref too). Probably only `en`?

**Comment by philwareham** [comment]
I'd prefer not to add a string unless this goes into a release. Let me know. Ta!

**Comment by Bloke** [comment]
It'll be exposed in 4.8.5 (in Advanced prefs, so hidden behind that setting) but what Oleg is alluding to is that this pref's very existence is transitory. Its exposure will allow people to test in the 4.8.x branch whether setting it to 0 breaks any plugins. If we don't hear any fallout then we can remove the pref (and probably the secondpass feature) in 4.9.

So the question: is it worth adding translations for a pref that's likely going to be removed next version?

**Comment by philwareham** [comment]
It's not just the preference - there will need to be a pophelp to explain it too. If you can supply me both I'll add them in (and yes, it'd be available on Crowdin but we can always remove again in future if pref is removed (it just means a little translation effort is wasted - but that's not the end of the world I guess).

**Comment by bloatware** [comment]
I don't really know how to explain it without being too technical. It's the maximum number of additional parser passes (currently 1) before it renders the processed page. Normally, the first pass suffices (all tags get processed), but some people use hacks postponing tags for ulterior processing. A stupid example would be
```
<txp:variable name="test" value="<txp:variable name='test' />" />
```
Each time it is parsed, it reproduces itself, i.e. `<txp:variable name='test' />`, so another round is needed to process the page. This opens potential security holes and I would like our users to check whether we can get rid of these constructions via new txp powers.

**Comment by Bloke** [comment]
Pref name: Number of extra parser sweeps

Help:
-----------------------
The Textpattern tag parser usually replaces all its tags with content from the database in one sweep of the page template. In some cases, this may be insufficient, for example:

* When using low load order plugins as tag attributes.
* Code replacements inside `<txp:php>` tags.
* Skipping page elements earlier in the page so they may receive content that is derived from a tag that is processed later.

If you find unprocessed tags being rendered on your website (and there are no other tag errors shown in Testing/Debugging modes due to mismatched tag pairs) then try increasing this value from its default of 0 to a higher number. And if you do find such an example, please contact us with your page template/code/plugin example. We are trying to eradicate the need for extra parser passes, and this information will help us achieve that.
-----------------------

How's that? Anybody got any improvements to make that simpler?

**Comment by bloatware** [comment]
Fine, but its default value is 1, so I would rather say 'try setting it to 0 to make your site more secure'.

**Comment by Bloke** [comment]
D'oh! Okay. So we need to reword that a bit to take that into account. Hang on...

**Comment by Bloke** [comment]
The Textpattern tag parser usually replaces all your tags with content from the database in one sweep of the page template. In some cases, this may be insufficient, for example:

* When using low load order plugins as tag attributes.
* Code replacements inside <txp:php> tags.
* Skipping page elements earlier in the page so they may receive content that is derived from a tag that is processed later.

Textpattern has traditionally run one extra sweep (called `secondpass`) for legacy reasons, hence the default value of this preference being 1. More sweeps, however, increase the chances of unintended tags slipping through and being processed. Recent improvements in the tag parser have reduced the need for this second pass. So, unless you are using the second sweep for a dedicated reason, please reduce this value to 0 to make your site more secure.

If you subsequently find unprocessed tags being rendered on your website (and there are no other tag errors shown in Testing/Debugging modes due to mismatched tag pairs) then please contact us with your page template/code/plugin example. We are trying to eradicate the need for extra parser passes, and this information will help us achieve that.

**Comment by bloatware** [comment]
Yep, if this sounds as 'try to avoid extra passes', it's fine.

**Comment by philwareham** [comment]
I've added this text into the 'en' language pack only. Closing for now.
